name: Shellcheck
on: [push]

jobs:
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Shellcheck
      run: |
        npm run vet

